[build]
  base = "project"
  command = "cd project && npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  git_branch = "main"
  git_repository = "github.com/pxd1213/energylinkparser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
