[build]
  base = "project"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  git_branch = "main"
  git_repository = "github.com/pxd1213/energylinkparser"

[context.production.environment]
  VITE_OPENAI_API_KEY = "${{secrets.OPENAI_API_KEY}}"
  OPENAI_API_KEY = "${{secrets.OPENAI_API_KEY}}"
  API_KEY = "${{secrets.OPENAI_API_KEY}}"
  OPENAI_API_KEY_VALUE = "${{secrets.OPENAI_API_KEY}}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
