[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  git_branch = "main"
  git_repository = "github.com/pxd1213/energylinkparser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
