[build]
  base = "project"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  git_branch = "main"
  git_repository = "github.com/pxd1213/energylinkparser"

[context.production.environment]
  OPENAI_API_KEY = "${{secrets.OPENAI_API_KEY}}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions.node_version]
  external_node_modules = []
  version = "20"

[functions.openai]
  memory_size = 1024
  timeout = 30
